### ISSUE TITLE
Really slow performances

### ISSUE THREAD

**Issue by tecufanujacu** [ptrsr/pi-ci#5]
Hello there, thanks for this project.

I'm trying it in my desktop with Debian 9 but in pi-ci I'm having really really slow i/o and network performances that make it almost unusable.

I/O in my desktop:

```
time dd if=/dev/zero of=test.dat bs=1024 count=100000
100000+0 record dentro
100000+0 record fuori
102400000 bytes (102 MB, 98 MiB) copied, 0,314238 s, 326 MB/s

real	0m0,356s
user	0m0,048s
sys	0m0,256s
```

I/O in pi-ci:
```
100000+0 records in
100000+0 records out
102400000 bytes (102 MB, 98 MiB) copied, 62.5928 s, 1.6 MB/s

real	1m2.874s
user	0m8.865s
sys	0m49.498s
```

Network speed in my desktop:
```
Download: 19.81 Mbit/s
Upload: 18.49 Mbit/s
```

Network speed in pi-ci:
```
Download: 1.04 Mbit/s
Upload: 1.00 Mbit/s
```

I also tested pi-ci in a vm with debian 10 in my proxmox server with almost same results.
Are these the expected performances or I'm having problems?

**Comment by tecufanujacu** [comment]
Thanks for your quick feedback. I imagined that the low speed was caused by the arm emulation but I preferred to be sure.
Obviously I didn't consider this project a replacement for an RPi, I would use it to prepare a customized image with several packages installed and configured to install on RPi but considered that a simple apache install took a lot of time I decided to ask before of continuing.

About I/O performance I agree, you have 5 time faster speed thanks of nvme ssd that I don't have.
About network speed me to I have used speedtest-cli in the same way of you.

Just a last question, could you better explain me what do you mean with "continuous integration pipelines that runs in the background"? For example how you would affront an apache webserver install and configuration?

Anyway thanks for the work behind this project, in case I will not be able to speed up the customization procedure then I will have patience :-)

**Comment by ptrsr** [comment]
Good question! To answer it, I'll have to explain a bit about how this project came to be.

Like you, I originally intended to use the Raspberry Pi as a server. In order to achieves this, you have to tweak the configuration of the system quite a bit. Create a new user, install dependencies, security measures, etc. In the case that the SD card corrupts, you'll lose a lot of important data and settings. Regular backups are an option, but far from ideal. What if due some software version mismatch your configuration breaks and you want a fresh install? Or if you want to upgrade to a new version of your distro? What if you want to provision system configurations? You can make a manual, but who likes going through 30 steps to install and configure a system from scratch? 

Ideally, you want some kind of blueprint. Something that allows you to flash a server configuration on a RPi with a single press of a button. This is what PI-CI intends to achieve; to make your Raspberry Pi's system configuration reproducible.

## How does one go about making a system configuration reproducible? A few steps;
1. Use PI-CI to flash a fresh image to an SD card.
2. Create a git repo on the RPi, share it with your PC.
3. Write reproducible Ansible playbooks to setup a system configuration.
4. Run the playbooks on the physical RPi.
5. Run the playbooks on the emulator RPi.
6. Flash the emulator image to a second SD card, check if result is as expected.
7. Setup a CI pipeline (such as GitHub Actions) to run these playbooks using PI-CI and upload the resulting images as artifacts.
8. Flash and test the image produced by the CI pipeline.

Congratulations, your system is reproducible. The Ansible scripts are your blueprint. Develop using the physical Pi, and occasionally test the virtual Pi images that have been build in the background by your CI pipeline. You can combine Ansible with Python or shell scripts if you prefer those approaches.

Conclusion: PI-CI is more like a smart backup tool that runs in the background, rather than a development environment.

**Comment by tecufanujacu** [comment]
Understood, so it is mainly a backup tool and not a development tool. Unfortunatly this isn't suitable for my use case, I should prepare an image without having a rasp.

**Comment by andrewcooke** [comment]
sorry for commenting here, but i don't see where else to get support / ask questions.

i think i understand this project at a basic level - it runs qemu in docker and within qemu runs a raspberry pi.  you configure the raspberry pi and then can copy the files system to an image.  please tell me if i'm wrong!

but there are at least two things i am confused by.

first, apparently qemu only support rpi 2 and 3, but you say (somewhere) this doesn't matter - you can run the image on rpi4.  that seems odd.  if the image works on rpi4 then why doesn't qemu emulate rpi4?  what's the difference between 3 and 4 that makes no difference to the image but affects qumu?  as i write this i guess maybe i can understand if it's the same instruction set but somehow different hardware in other ways?

second, in the example above with numbered steps, could i just do steps 3, 5 and 6?  are the other steps necessary or just if you want to check things (do they often fail?) or have some kind of ongoing process?

thanks in advance for any answer (and also thanks for making this; even if i hear nothing i will probably download it and play around - it seems like exactly what i need).

**Comment by ptrsr** [comment]
@andrewcooke 
> sorry for commenting here, but i don't see where else to get support / ask questions.

No problem!

> i think i understand this project at a basic level - it runs qemu in docker and within qemu runs a raspberry pi. you configure the raspberry pi and then can copy the files system to an image. please tell me if i'm wrong!

You're almost correct. When you start PI-CI, it creates a virtual image for you (the `qcow2` file). You can work in this virtual image and the changes will be saved in there. At any point, you can flash this virtual image to a physical SD card for a real Raspberry PI to run.

> but there are at least two things i am confused by.
> 
> first, apparently qemu only support rpi 2 and 3, but you say (somewhere) this doesn't matter - you can run the image on rpi4. that seems odd. if the image works on rpi4 then why doesn't qemu emulate rpi4? what's the difference between 3 and 4 that makes no difference to the image but affects qumu? as i write this i guess maybe i can understand if it's the same instruction set but somehow different hardware in other ways?

You're not the first person to get confused by this, let me explain;
PI-CI is currently configured to run as a Raspberry Pi 3 through QEMU. This can be changed to other [supported boards](https://www.qemu.org/docs/master/system/arm/raspi.html),  but not without modifying PI-CI. Unfortunately, QEMU does not support a virtual Pi 4 board. Luckily the Pi 3 & 4 are very similar; they can both run `32` and `64` bit ARM images (called `ARMv7` and a `ARMv8` respectfully). The Pi 2 however can only run `32` bit. **PI-CI comes with a** `raspios-buster-arm64-lite` (an `ARMv8` image). Meaning that the included image runs on both the Pi 3 & 4, but **NOT** the 2. In theory, you could replace the included `image.qcow2` with your own `ARMv7` image and probably run it on the Pi 2, 3, and 4.

> second, in the example above with numbered steps, could i just do steps 3, 5 and 6? are the other steps necessary or just if you want to check things (do they often fail?) or have some kind of ongoing process?

Yes you certainly can, although it won't be fast though (which was the main problem of this original issue). I would recommend making regular backups of the `image.qcow2` file, so that you do not have to start from scratch if the system corrupts virtual image corrupts (emulators aren't perfect). If you need any help with Ansible and/or reproducibility, please make a new issue. Thanks!

**Comment by leadcrafter** [comment]
For M1 Mac Users:

To Fix "Really slow Performance" just turn on Rosetta for virtualization in Docker Setup.
