### ISSUE TITLE
Unraid Docker

### ISSUE THREAD

**Issue by lyrics1988123** [ptrsr/pi-ci#9]
Hello!

Thats a nice project, i was looking for exactly this. 
Would you mind put it on the unraid community apps? 

thanks :)

**Comment by ptrsr** [comment]
Hi @lyrics1988123 ,

Thank you so much for your kind words! I'm familiar with the unRAID project. However, I'm not using it myself. I'm planning to release my own hosting solution soon using this project. I encourage anyone to release PI-CI on unRAID themselves, though! I made this project open source so that anyone can use it. I only ask to give back improvements to the original project :)

If you have any questions, feel free to contact me. Do you mind me closing this GitHub issue?

Best,
Ruud

**Comment by lyrics1988123** [comment]
sure close it :)
thanks for the reply and infos!
